# Generated by Django 4.2.23 on 2025-08-03 23:37

from django.db import migrations, models
from django.contrib.postgres.search import SearchVector


def populate_search_vectors(apps, schema_editor):
    """Populate search_vector field for all existing documents."""
    Document = apps.get_model('documents', 'Document')
    
    # Update in batches to handle large datasets efficiently
    batch_size = 1000
    documents = Document.objects.all()
    total_count = documents.count()
    
    print(f"Updating search vectors for {total_count} documents...")
    
    for i in range(0, total_count, batch_size):
        batch = documents[i:i + batch_size]
        
        for document in batch:
            # Extract plain text from content (simplified version for migration)
            content_text = extract_plain_text_simple(document.content)
            
            # Update search vector
            Document.objects.filter(pk=document.pk).update(
                search_vector=(
                    SearchVector('title', weight='A') +
                    SearchVector(models.Value(content_text), weight='B')
                )
            )
        
        print(f"Processed {min(i + batch_size, total_count)} / {total_count} documents")


def extract_plain_text_simple(content):
    """
    Simplified plain text extraction for migration.
    This is a basic version that works within the migration context.
    """
    if not content or not isinstance(content, dict):
        return ""
    
    def extract_from_nodes(nodes):
        if not isinstance(nodes, list):
            return ""
        
        text_parts = []
        for node in nodes:
            if not isinstance(node, dict):
                continue
            
            if node.get("type") == "text":
                text_parts.append(node.get("text", ""))
            elif "children" in node:
                text_parts.append(extract_from_nodes(node["children"]))
            elif "content" in node:
                text_parts.append(extract_from_nodes(node["content"]))
        
        return " ".join(text_parts)
    
    # Handle both standard Lexical format and alternative format
    root_children = content.get("root", {}).get("children", [])
    if not root_children:
        root_children = content.get("content", [])
    
    return extract_from_nodes(root_children).strip()


def reverse_populate_search_vectors(apps, schema_editor):
    """Reverse migration - clear search vectors."""
    Document = apps.get_model('documents', 'Document')
    Document.objects.update(search_vector=None)


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_add_search_vector"),
    ]

    operations = [
        migrations.RunPython(
            populate_search_vectors,
            reverse_populate_search_vectors,
        ),
    ]
